//
//  ListWorker.swift
//  ToDoProject
//
//  Created by ozgun on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


// MARK: - Todos store API



class ListWorker {
    var coreData: CoreDataManagerProtocol
    var notificationManager: NotificationManagerProtocol
    
    init(coreData: CoreDataManagerProtocol, notificationManager: NotificationManagerProtocol) {
        self.coreData = coreData
        self.notificationManager = notificationManager
    }

    func fetchTodos(completionHandler: @escaping ([TodoItem]) -> Void) {
        let todos = coreData.fetchTodoList()
        DispatchQueue.main.async {
            completionHandler(todos)
        }
    }
    
    func fetchTodos(with text: String, completionHandler: @escaping ([TodoItem]) -> Void) {
        let todos = coreData.searchTodo(with: text)
        DispatchQueue.main.async {
            completionHandler(todos)
        }
    }

    func checkTodo(with id: Int, row: Int, completionHandler: @escaping (Int, TodoItem?) -> Void) {
        coreData.checkTodo(id: Int64(id)) { (row: () throws -> Int, todo: TodoItem?) -> Void in
            do {
                let row = try row()
                DispatchQueue.main.async {
                    completionHandler(row, todo)
                }
            } catch {
                DispatchQueue.main.async {
                    completionHandler(0, nil)
                }
            }
        }
    }
    
    func deleteTodo(with id: Int, row: Int, completionHandler: @escaping (Int) -> Void) {
        coreData.deleteTodo(id: Int64(id)) { onSuccess in
            DispatchQueue.main.async {
                completionHandler(row)
            }
        }
    }
    
    func deleteNotification(with notificationId: String) {
        
        notificationManager.deleteNotification(with: notificationId) { onSuccess in
            print(onSuccess)
        }
    }
    
    
}




