//
//  ListRouter.swift
//  ToDoProject
//
//  Created by ozgun on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListRoutingLogic {
    func routeToCreateTodo(segue: UIStoryboardSegue?)
    func routeToDetailTodo(index: Int, id: Int)
}

protocol ListDataPassing {
    var dataStore: ListDataStore? { get }
}

class ListRouter: NSObject, ListRoutingLogic, ListDataPassing {
    
      weak var viewController: ListViewController?
      var dataStore: ListDataStore?
  
    // MARK: Routing
  
    func routeToCreateTodo(segue: UIStoryboardSegue?) {
        if segue == nil {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
            destinationVC.editButton.title = ""
            navigateToDetailTodo(source: viewController!, destination: destinationVC)
        }
    }

    func routeToDetailTodo(index: Int, id: Int) {
        let storyboard = UIStoryboard(name: K.main, bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
        destinationVC.router?.dataStore?.todo = dataStore?.todos?[index]
        destinationVC.router?.dataStore?.id = id
        destinationVC.saveButton.title = ""
        self.viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    // MARK: Navigation
  
    func navigateToDetailTodo(source: ListViewController, destination: DetailViewController) {
        source.show(destination, sender: nil)
    }
  
}
