//
//  DetailViewController.swift
//  ToDoProject
//
//  Created by ozgun on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailDisplayLogic: AnyObject {
    func displayCreateTodo(viewModel: CreateTodo.CreateTodo.ViewModel)
    func displayTodo(viewModel: CreateTodo.FetchTodo.ViewModel)
}

class DetailViewController: UIViewController, DetailDisplayLogic {
   
  var interactor: DetailBusinessLogic?
  var router: (NSObjectProtocol & DetailRoutingLogic & DetailDataPassing)?

    @IBOutlet weak var titleTextField: UITextField!
    @IBOutlet weak var descriptionTextField: UITextField!
    @IBOutlet weak var datePicker: UIDatePicker!
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = DetailInteractor()
    let presenter = DetailPresenter()
    let router = DetailRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
      super.viewDidLoad()
      fetchDetail()
  }
  
    deinit {
        print("denitited")
    }
  // MARK: Do something
  
  // date eklenecek
    @IBAction func saveButtonTapped(_ sender: UIBarButtonItem) {
        let title = titleTextField.text
        let description = descriptionTextField.text
        if title != nil {
            let request = CreateTodo.CreateTodo.Request( todoField: CreateTodo.TodoField(title: title!, description: description ?? ""))
            interactor?.createTodo(request: request)
        }
        
    }
    func fetchDetail() {
        let request = CreateTodo.FetchTodo.Request()
        interactor?.fetchTodo(request: request)
    }

    func displayCreateTodo(viewModel: CreateTodo.CreateTodo.ViewModel) {
        print(viewModel.isSuccess as Any)
        guard let isSuccess = viewModel.isSuccess else {
            //log alert
            return
        }
        if isSuccess {
            router?.routeToTodoList(segue: nil)
            print("success")
//            router?.routeToTodoList(segue: nil)
        } else {
            // log alert
        }

    }
    func displayTodo(viewModel: CreateTodo.FetchTodo.ViewModel) {
        titleTextField.text = viewModel.title
        descriptionTextField.text = viewModel.descriptions
    }

}
