//
//  DetailWorker.swift
//  ToDoProject
//
//  Created by ozgun on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailStoreProtocol {
    func createTodo(title: String, description: String, completionHandler: @escaping (() throws -> Bool?) -> Void)

}
class DetailWorker {
    var todosStore: DetailStoreProtocol
    init(todosStore: DetailStoreProtocol)
    {
        self.todosStore = todosStore
    }
    
    func createTodo(title: String, description: String, completionHandler: @escaping (Bool?) -> Void)
    {
        todosStore.createTodo(title: title, description: description) {
            (success: () throws -> Bool?) -> Void in
            do {
                let success = try success()
                DispatchQueue.main.async {
                    completionHandler(success)
                }
            } catch {
                DispatchQueue.main.async {
                    completionHandler(nil)
                }
            }
        }
    }
}
