//
//  DetailInteractor.swift
//  ToDoProject
//
//  Created by ozgun on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func createTodo(request: DetailTodo.CreateTodo.Request)
    func fetchTodo(request: DetailTodo.FetchTodo.Request)
    func editTodo(request: DetailTodo.EditTodo.Request)
    func editTime(request: DetailTodo.EditTime.Request)
}

protocol DetailDataStore {
    var id: Int? { get set }
    var todo: TodoItem? { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    
    
    var id: Int?
    var todo: TodoItem?
    
    var presenter: DetailPresentationLogic?
    var worker = DetailWorker(todosStore: TodoStore())
  
  // MARK: CRUD operations
  
    func createTodo(request: DetailTodo.CreateTodo.Request) {
        let title = request.todoField.title
        let description = request.todoField.description
        worker.createTodo(title: title, description: description) { (isSuccess: Bool?) in
            let response = DetailTodo.CreateTodo.Response(isSuccess: isSuccess)
            self.presenter?.presentCreateTodo(response: response)
        }
    }
                                              
    
    func fetchTodo(request: DetailTodo.FetchTodo.Request) {
        self.presenter?.presentTodo(response: .init(todo: todo))
    }
    func editTodo(request: DetailTodo.EditTodo.Request) {
        let title = request.todoField.title
        let description = request.todoField.description
        worker.editTodo(id: id!, title: title, description: description) { (isSuccess: Bool?) in
            let response = DetailTodo.EditTodo.Response(isSuccess: isSuccess)
            self.presenter?.presentEditTodo(response: response)
        }
    }
    func editTime(request: DetailTodo.EditTime.Request) {
        let time = request.todoField.notificationDate
        worker.editTime(id: id!, time: time) { (isSuccess: Bool?) in
            let response = DetailTodo.EditTime.Response(isSuccess: isSuccess)
            self.presenter?.presentEditTime(response: response)
        }
    }
    
}
