//
//  DetailInteractor.swift
//  ToDoProject
//
//  Created by ozgun on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func createTodo(request: CreateTodo.CreateTodo.Request)
    
}

protocol DetailDataStore {
  //var name: String { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var presenter: DetailPresentationLogic?
    var worker = DetailWorker(todosStore: TodoStore())
  //var name: String = ""
  
  // MARK: Do something
  
    func createTodo(request: CreateTodo.CreateTodo.Request) {

        let title = request.todoField.title
        let description = request.todoField.description

        worker.createTodo(title: title, description: description) { (isSuccess: Bool?) in

            let response = CreateTodo.CreateTodo.Response(isSuccess: isSuccess)
            self.presenter?.presentCreateTodo(response: response)

        }

    }
}
