//
//  DetailPresenter.swift
//  ToDoProject
//
//  Created by ozgun on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentCreateTodo(response: CreateTodo.CreateTodo.Response)
}

class DetailPresenter: DetailPresentationLogic {
    
    
    weak var viewController: DetailDisplayLogic?
  
  
    func presentCreateTodo(response: CreateTodo.CreateTodo.Response) {
        let viewModel = CreateTodo.CreateTodo.ViewModel(isSuccess: response.isSuccess)
        viewController?.displayCreateTodo(viewModel: viewModel)
    }
}
