//
//  DetailPresenter.swift
//  ToDoProject
//
//  Created by ozgun on 31.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentCreateTodo(response: DetailTodo.CreateTodo.Response)
    func presentTodo(response: DetailTodo.FetchTodo.Response)
    func presentEditTodo(response: DetailTodo.EditTodo.Response)

}

class DetailPresenter: DetailPresentationLogic {
    
    weak var viewController: DetailDisplayLogic?
    
    
    func presentCreateTodo(response: DetailTodo.CreateTodo.Response) {
        let viewModel = DetailTodo.CreateTodo.ViewModel(isSuccess: response.isSuccess)
        viewController?.displayCreateTodo(viewModel: viewModel)
    }
    
    func presentTodo(response: DetailTodo.FetchTodo.Response) {
        
        let viewModel = DetailTodo.FetchTodo.ViewModel(title: response.todo?.title ?? "", descriptions: response.todo?.descriptions ?? "")
        viewController?.displayTodo(viewModel: viewModel)
    }
    func presentEditTodo(response: DetailTodo.EditTodo.Response) {
        
        let viewModel = DetailTodo.EditTodo.ViewModel(isSuccess: response.isSuccess)
        viewController?.displayEditTodo(viewModel: viewModel)
    }
}

